# Generated by Django 5.2.12 on 2026-03-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Segunda-Feira'), ('tue', 'Terça-Feira'), ('wed', 'Quarta-Feira'), ('thu', 'Quinta-Feira'), ('fri', 'Sexta-Feira'), ('sat', 'Sábado'), ('sun', 'Domingo')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
