# Generated by Django 5.2.12 on 2026-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='workouts.WorkoutExercise', to='workouts.exercise'),
        ),
    ]
